export default {
  CREATE: 'CREATE_room',
  CREATE_SUCCESS: 'CREATE_SUCCESS_room',
  UPDATE: 'UPDATE_room',
  UPDATE_SUCCESS: 'UPDATE_SUCCESS_room',
  DELETE: 'DELETE_room',
  DELETE_SUCCESS: 'DELETE_SUCCESS_room',
  GET: 'GET_room',
  GET_SUCCESS: 'GET_SUCCESS_room',
  LIST: 'LIST_room',
  LIST_SUCCESS: 'LIST_SUCCESS_room',
  GET_COMMENT_TOTAL_COUNT: 'GET_COMMENT_TOTAL_COUNT',
  GET_COMMENT_TOTAL_COUNT_SUCCESS: 'GET_COMMENT_TOTAL_COUNT_SUCCESS',
};
