export default {
  CREATE: 'CREATE',
  CREATE_SUCCESS: 'CREATE_SUCCESS',
  UPDATE: 'UPDATE',
  UPDATE_SUCCESS: 'UPDATE_SUCCESS',
  DELETE: 'DELETE',
  DELETE_SUCCESS: 'DELETE_SUCCESS',
  GET: 'GET',
  GET_SUCCESS: 'GET_SUCCESS',
  LIST: 'LIST',
  LIST_SUCCESS: 'LIST_SUCCESS',
};
